name: Secret Demo

on:
  push:
    branches:
      - main

jobs:
  show-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Exibir mensagem de secret
        run: |
          if [ -n "${{ secrets.API_KEY }}" ]; then
            echo "API_KEY configurado"
          else
            echo "API_KEY não encontrado"
          fi
