name: Run Tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Rodando testes
        run: echo "Rodando testes"
